import { Injectable, Pipe, PipeTransform } from '@angular/core';

@Pipe({
 name: 'lang'
})

@Injectable()
export class LangPipe implements PipeTransform {
 transform(key: string) {
   return this.he[key];
  }

 he = {
    "accessbility": "נגישות",
    "fasterInAppliction": " יותר מהר באפליקציה",
    "loading": "טוען...",
    "searchInSite": "חפש באתר",
    "reg": "הרשמה",
    "Logination": "התחברות",
    "vocalMesseg": "הודעה קולית",
    "phoneNumberNotValid": "מספר טלפון אינו חוקי",
    "vocalMesDes": "במידה ואין באפשרותך לקבל הודעה,",
    "vocalMesDes1": "תוכל/י לבחור לקבל את הקוד באמצעות",
    "notRobot": "אנא אשר שאינך רובוט",
    "approvedCond": "מאשר תנאי השימוש בכפוף ל",
    "approved": "מאושר",
    "vocalMesDes2": "הודעה קולית בלחיצה על הכפתור",
    "chooseSity": "בחר עיר/רשות",
    "chooseSity1": "בחרו רשות/ תאגיד מים",
    "firstName": "שם פרטי",
    "LastName": "שם משפחה",
    "email": "דואר אלקטרוני",
    "tzPayer": " תעודת זהות/מספר משלם",
    "phone": "מספר נייד",
    "insertPhoneNumber": "הזן מספר נייד",
    "voiceMesseg": "הודעה קולית",
    "letsStart": "בואו נתחיל!",
    "formSupport": "לתמיכה במילוי הטופס, ניתן לפנות למספר: ",
    "cantGetMesseg1": "במידה ואין באפשרותך לקבל הודעה,",
    "cantGetMesseg2": "תוכל/י לבחור לקבל את הקוד באמצעות",
    "cantGetMesseg3": "הודעה קולית בלחיצה על הכפתור",
    "iChangePhoneNumber": "החלפת מספר טלפון? לחץ כאן",
    "confirmByMessegText1": "נבקש כעת לאמת את זהותך",
    "confirmByMessegText2": "באמצעות קוד חד-פעמי",
    "confirmByMessegText3": "שנשלח למכשירך",
    "rememberMe": "זכור אותי",
    "regulations": "תקנון",
    "send": "שלח/י",
    "assetNumber": "מספר נכס",
    "insertAssetNumberDescMesseg1": "הוסף את מס הנכס המוצג בשובר התשלום שנשלח",
    "insertAssetNumberDescMesseg2": "בדואר או בחשבונית התשלום שהתקבלה בדואל",   
    "assetNumberErrorMesseg": "מס' הנכס שגוי, אנא מלאו מחדש או תנו לנו לעזור לכם מרחוק בעזרת מסך גלגל ההצלה שלנו.",
    "stayRegToWaterCor": "הישאר רשום לרשות המים",
    "stayRegToLocalCor": "הישאר רשום לרשות המקומית",
    "city": "עיר",
    "street": "רחוב",
    "": "",
    "insert": "הוסף",  
    "phoneExistsInSystem": "מספר טלפון כבר קיים במערכת",
    "chooseCityFromTheList": "בחר עיר מתוך הרשימה",
    "chooseStreetFromTheList": "בחר רחוב מתוך הרשימה",
    "forYouIs": "עבורך זה",
    "MunicipalServicesPlus": "לשירותים דיגיטליים לרשויות ותאגידים – תשלומים, טפסים, זימון תורים, ניהול פניות, דווח מפגעים, שוברים במייל ועוד. בכמה שלבים פשוטים.",
    "phoneNumberNotFoundInSystem": "המספר אינו מזוהה. להרשמה לחץ",
    "here": "כאן",
    "insertTheCode": "הזן את הקוד",
    "codeDontCorrect": "קוד אינו נכון- אנא נסה שנית.",
    "clickToDownload": "לחץ להורדה",
    "MunicipalServices": "שירותים דיגיטליים",
    "approvalRegulations1": "מאשר הרשמה לשירותים הדיגיטליים וקבלת שירותים וחידושים נוספים לרבות מידע עירוני בכפוף ל-",
    "approvalRegulations2": "ותנאי השימוש ומדיניות הפרטיות של החברה",
    "whichServicesYouWantToGet": "אילו שירותים תרצו לקבל?",
    "identificationCodeFromMail": "אם יש בידכם טופס מהדואר, הזינו קוד זיהוי",
    "setIdentificationCode": "הזנת קוד זיהוי",
    "OK": "אישור",
    "cancel": "ביטול",
    "replacementHolders": "החלפת מחזיקים",
    "forms": "טפסים חכמים",
    "Appointments": "זימון תורים",
    "Payments": "תשלומים",
    "WaterDetails": "נתוני מים",
    "MailBills": "חשבוניות במייל",
    "paymentOptions": "אפשרויות תשלום",
    "services": "שירותים",
    "personalArea": "איזור אישי",
    "logOut": "התנתק",
    "switch": "החלף",
    "addCorporation": "הוסף רשות",
    "newsAndUpdates": "חדשות ועדכונים",
    "paymentVouchers": "שוברים לתשלום",
    "updatePersonalDetails": "עדכון פרטים אישיים",
    "corporationManagment": "ניהול רשות/תאגיד",
    "myVouchers": "השוברים שלי",
    "date": "תאריך",
    "subject": "נושא",
    "voucherNumber": "מספר שובר",
    "status": "סטטוס",
    "paymentPlace": "מקום התשלום",
    "watchTheVoucher": "צפיה בשובר",
    "payment": "תשלום",
    "summaryPayment": "סכום",
    "whereFindTheCode": "איפה מוצאים את הקוד?",
    "helloGuest": "שלום אורח!",
    "logIn": "התחבר",
    "ChatWithRepresentative": "צא'ט עם נציג",
    "backTotheMainMenu": "חזרה לתפריט הראשי",
    "paymentsAreaMesseg": "אזור התשלומים מאפשר תשלום באשראי של חשבונות שונים, רישום לאזור זה יאפשר עדכונים שוטפים של חשבונות חדשים לתשלום",
    "isValidRegulations": "חובה לאשר את התקנון",
    "hello": "שלום",
    "corporation": "תאגיד",
    "payBills": "תשלום חשבונות",
    "activeUsers": "משתמשים פעילים",
    "fullName": "שם מלא",
    "addOrDeleteAnotherPhone": "הוספת / הסרת טלפון נוסף לביצוע פעולות בחשבון",
    "creditDetail": "פרטי אשראי",
    "payerNumber": "מספר משלם",
    "lastFourNumber": "ארבע ספרות אחרונות של כרטיס אשראי",
    "changeCreditDetail": "החלפת פרטי כרטיס אשראי", 
    "myDetails": "הפרטים שלי",
    "addTown": "הוסף ישוב",
    "corpration": "רשות/תאגיד",
    "myAssets": "הנכסים שלי",
    "theNumberAsset": "מספר הנכס",
    "delete": "הסר",
    "newPhoneNumber": "מספר טלפון חדש",
    "newEmail": "דואר אלקטרוני חדש",
    "areYouSure": "האם אתה בטוח?",
    "bothEmptyMesseg": "אנא הזן לפחות תא אחד",
    "assetNotExsist": "פרטי הנכס לא נמצאו או אינם תואמים לת.ז",
    "month": "חודש",
    "addres": "כתובת",
    "name": "שם",
    "waterIdentification": "כרטיס מים",
    "counter": "מד",
    "consumption": "צריכה",
    "aboutTheCompeny": "אודות הרשות",
    "regAndLogIn": "התחברות והרשמה",
    "back": "חזרה",
    "Number": "מספר",
    "callTo106": "פניה למוקד 106",
    "prevCallTo106": "פניות קודמות למוקד 106",
    "Description": "תיאור",
    "addImageEvent": " להוספת צילום של המפגע ", 
    "filedMustHebLetters": "שדה זה חייב להיות מורכב מאותיות בעברית בלבד",
    "openDate": "תאריך פתיחה",
    "isValidExsistsPhone": "מספר הטלפון או תעודת הזהות כבר קיים במערכת",
    "changeCreditDitail": "החלף פרטי אשראי",
    "payed": "שולם",
    "noPayed": "לא שולם",
    "assetDeleted":"הנכס נמחק בהצלחה!",
  
    
    "v-a-l-i-d-a-t-i-o-n": "*****************",
    "filedMust": "שדה זה הינו שדה חובה",
    "MustFirstName": "שם פרטי הינו שדה חובה",
    "MustLastName": "שם משפחה הינו שדה חובה",
    "MustEmail": "כתובת אימייל הינה שדה חובה",
    "MustPhone": "טלפון הינו שדה חובה",
    "MustTZ": "תעודת זהות הינה שדה חובה",
    "MuststreetName": "שם רחוב הינו שדה חובה",
    "MustAssetNumber": "מספר נכס הינו שדה חובה",
    
    "FirstNameMustHebLetters": "שם פרטי חייב להיות מורכב מאותיות בעברית בלבד", 
    "LastNameMustHebLetters": "שם משפחה חייב להיות מורכב מאותיות בעברית בלבד",  
  
    "invalidEmail": "כתובת אימייל אינה חוקית",
    "invalidPhone": "מספר טלפון אינו חוקי",
    "invalidPhoneLength": "מספר טלפון חייב להיות באורך של עשר ספרות",  
    "invalidTZ": "מספר תעודת זהות אינו חוקי",
   
    "minimumTwoLetters": "חובה להזין לפחות שתי אותיות",
    "payerNumberisMustFiled": "מספר משלם הינו שדה חובה",
    "passportisMustFiled": "דרכון הינו שדה חובה",
    "generalisMustFiled": "שדה זה הינו שדה חובה",
    "payerNumberMustSevenLetters" : "מספר משלם חייב להיות גדול משש ספרות",
    "restPhoneMustSevenLetters" : "מספר טלפון ללא קידומת חייב להיות בעל שבע ספרות",
    "restPhoneisMustFiled" : "מספר טלפון הינו שדה חובה",
    
    "streetNumIsMust": "מספר רחוב הינו שדה חובה",
    "numStreetNotValid": "מספר רחוב אינו חוקי",
   
    "streetNameMustHebLetters": "שם רחוב חייב להיות מורכב מאותיות בעברית בלבד",
    "chooseFromTheList" : "בחר מתוך הרשימה",
    "myOpend": "הפניות שלי",
    "midotArnona": "מידות ארנונה",
    "myDocuments": "המסמכים שלי",
    "invalidAssetNumber": "מספר נכס אינו חוקי",
    "invalidAssetNumberLength": "מספר נכס חייב להיות גדול מארבע ספרות",
   
    "chipMust15Letters": "שבב חייב להיות באורך של 15 תווים",
    "chipisMustFiled": "שבב הינו שדה חובה"
  
  }









}



